package com.hashnightflux.vag.datagen;

import com.hashnightflux.vag.Reference;
import com.hashnightflux.vag.common.GripType;
import com.hashnightflux.vag.common.Gun;
import com.hashnightflux.vag.init.ModItems;
import com.hashnightflux.vag.init.ModSounds;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;

import java.util.concurrent.CompletableFuture;

/**
 * Author: MrCrayfish
 */
public class GunGen extends GunProvider
{
    public GunGen(PackOutput output, CompletableFuture<HolderLookup.Provider> registries)
    {
        super(output, registries);
    }

    @Override
    protected void registerGuns()
    {
        this.addGun(new ResourceLocation(Reference.MOD_ID, "boltcaster"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(3)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(40)
                .setReloadAmount(10)
                .setRecoilKick(0.25F)
                .setRecoilAngle(3.0F)
                .setSpread(4.0F)
                .setAmmo(ModItems.POWDERED_PELLET.get())
                .setDamage(6.5F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10F)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_BOLTCASTER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setCockSound(ModSounds.ITEM_BOLTCASTER_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_BOLTCASTER_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_BOLTCASTER_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6, -6.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.2, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -5.9)
                .setStock(1.0F, 0.0, 3.6, 8.2)
                .setUnderBarrel(1.0F, 0.0, 2.799, -1.0)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "dynamite_launcher"), Gun.Builder.create()
                .setFireRate(20)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(1)
                .setRecoilAngle(5.0F)
                .setRecoilKick(1.0F)
                .setRecoilDurationOffset(0.25F)
                .setAmmo(ModItems.DYNAMITE.get())
                .setDamage(15.0F)
                .setProjectileVisible(true)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(1.5F)
                .setProjectileLife(50)
                .setProjectileAffectedByGravity(true)
                .setFireSound(ModSounds.ITEM_DYNAMITE_LAUNCHER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setMuzzleFlash(0.75, 0.0, 3.5, -3.8)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.7, 3.0))
                .setScope(1.0F, 0.0, 5.2, 2.7)
                .setStock(1.0F, 0.0, 3.6, 8.2)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "musket"), Gun.Builder.create()
                .setFireRate(40)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(4)
                .setReloadAmount(1)
                .setRecoilAngle(10.0F)
                .setRecoilKick(1.0F)
                .setRecoilDurationOffset(0.5F)
                .setRecoilAdsReduction(0.4F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.BOLT.get())
                .setDamage(18.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(25.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_MUSKET_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setCockSound(ModSounds.ITEM_MUSKET_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_MUSKET_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_MUSKET_ENCHANTED_FIRE.get())
                .setMuzzleFlash(1.0, 0.0, 3.6, -9.41)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 5.1, 2.0))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6, -9.4)
                .setUnderBarrel(1.0F, 0.0, 3.0, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "minimach"), Gun.Builder.create()
                .setAuto(true)
                .setFireRate(2)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(80)
                .setReloadAmount(20)
                .setRecoilAngle(4.0F)
                .setRecoilKick(0.25F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(6.0F)
                .setAmmo(ModItems.POWDERED_PELLET.get())
                .setDamage(3.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(20)
                .setFireSound(ModSounds.ITEM_MINIMACH_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SIDEHAMMER_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_MINIMACH_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_MINIMACH_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.35, 0.0, 3.5, 1.79)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.8F)
                        .setOffset(0.0, 4.8, -1.0))
                .setScope(1.0F, 0.0, 4.0, 5.5)
                .setBarrel(0.5F, 0.0, 3.2, 2.2)
                .setStock(1.0F, 0.0,3.2, 8.2)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "handcannon"), Gun.Builder.create()
                .setFireRate(4)
                .setGripType(GripType.ONE_HANDED)
                .setMaxAmmo(16)
                .setReloadAmount(4)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.POWDERED_PELLET.get())
                .setDamage(9.0F)
                .setProjectileSize(0.2F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(25)
                .setFireSound(ModSounds.ITEM_HANDCANNON_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setCockSound(ModSounds.ITEM_HANDCANNON_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_HANDCANNON_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_HANDCANNON_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.3, 2.64)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 4.5, -1.0))
                .setScope(0.75F, 0.0, 3.7, 6.0)
                .setBarrel(0.5F, 0.0, 3.3, 2.65)
                .setStock(1.0F, 0.0, 3.3, 7.95)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "sidehammer"), Gun.Builder.create()
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(10)
                .setReloadAmount(2)
                .setRecoilAngle(10.0F)
                .setRecoilKick(0.5F)
                .setRecoilAdsReduction(0.5F)
                .setAlwaysSpread(true)
                .setSpread(1.0F)
                .setAmmo(ModItems.BOLT.get())
                .setDamage(15.0F)
                .setProjectileAffectedByGravity(true)
                .setProjectileSize(0.0625F)
                .setProjectileSpeed(20.0F)
                .setProjectileLife(30)
                .setFireSound(ModSounds.ITEM_SIDEHAMMER_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setCockSound(ModSounds.ITEM_SIDEHAMMER_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_SIDEHAMMER_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_SIDEHAMMER_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.8365, -10.21)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.6F)
                        .setOffset(0.0, 4.6223, 6.0))
                .setScope(1.0F, 0.0, 4.3, 3.3)
                .setBarrel(0.45F, 0.0, 3.8365,-10.2)
                .setStock(1.0F, 0.0, 3.1294, 8.3)
                .setUnderBarrel(1.0F, 0.0, 2.63, -0.5)
                .build());

        this.addGun(new ResourceLocation(Reference.MOD_ID, "boomstick"), Gun.Builder.create()
                .setFireRate(8)
                .setGripType(GripType.TWO_HANDED)
                .setMaxAmmo(8)
                .setReloadAmount(2)
                .setRecoilKick(0.5F)
                .setRecoilAngle(10.0F)
                .setRecoilAdsReduction(0.4F)
                .setProjectileAmount(5)
                .setAlwaysSpread(true)
                .setSpread(20.0F)
                .setAmmo(ModItems.SHELL.get())
                .setDamage(18.0F)
                .setProjectileSize(1.0F)
                .setProjectileSpeed(10.0)
                .setProjectileLife(5)
                .setFireSound(ModSounds.ITEM_BOOMSTICK_FIRE.get())
                .setReloadSound(ModSounds.ITEM_HANDCANNON_RELOAD.get())
                .setCockSound(ModSounds.ITEM_BOOMSTICK_COCK.get())
                .setSilencedFireSound(ModSounds.ITEM_BOOMSTICK_SILENCED_FIRE.get())
                .setEnchantedFireSound(ModSounds.ITEM_BOOMSTICK_ENCHANTED_FIRE.get())
                .setMuzzleFlash(0.5, 0.0, 3.6505, -3.81)
                .setZoom(Gun.Modules.Zoom.builder()
                        .setFovModifier(0.7F)
                        .setOffset(0.0, 5.1, 3.2))
                .setScope(1.0F, 0.0, 4.4, 4.0)
                .setBarrel(0.5F, 0.0, 3.6506, -3.8)
                .setStock(1.0F, 0.0, 3.6506, 8.4)
                .build());
    }
}
